---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: rdr/amq_requirements
  labels:
    app: amq-sample
  name: amq-sub
spec:
    channel: ramen-busybox/ramen-gitops
    placement:
      placementRef:
        kind: PlacementRule
        name: amq-placement
